org: vasukiv
app: my-first-app
service: serverlessReact

name: deploy
stage: dev

deploy:
  component: '@serverless/website'
  inputs:
    code:
      src: ./build
      hook: npm run build
    region: us-east-2